name: C Template

inputs:
  pv_speaker_platform:
    required: true
  output_dir:
    required: true
  shell:
    required: false
    default: bash

runs:
  using: "composite"
  steps:
    - name: Create build directory
      run: cmake -B ./build -S . -DPV_SPEAKER_PLATFORM="${{ inputs.pv_speaker_platform }}" -DOUTPUT_DIR="${{ inputs.output_dir }}"
      working-directory: project
      shell: ${{ inputs.shell }}

    - name: Build
      run: cmake --build ./build
      working-directory: project
      shell: ${{ inputs.shell }}

    - name: Test
      run: ctest --output-on-failure
      working-directory: project/build
      shell: ${{ inputs.shell }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.pv_speaker_platform }}
        path: |
          lib/${{ inputs.output_dir }}/libpv_speaker.*
        retention-days: 3