name: .NET Codestyle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/dotnet/**/*.cs'
      - 'demo/dotnet/**/*.cs'
      - '.github/workflows/dotnet-codestyle.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/dotnet/**/*.cs'
      - 'demo/dotnet/**/*.cs'
      - '.github/workflows/dotnet-codestyle.yml'

jobs:
  check-dotnet-codestyle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Run Binding Codestyle
      run: dotnet format --verify-no-changes
      working-directory: binding/dotnet

      # ************** REMOVE AFTER RELEASE ********************
    - name: Pack .NET SDK
      run: dotnet pack -c Release
      working-directory: binding/dotnet

    - name: Add local NuGet package file
      run: dotnet add package -s ../../../binding/dotnet/PvSpeaker/bin/Release PvSpeaker
      working-directory: demo/dotnet/PvSpeakerDemo
      # ********************************************************

    - name: Run Demo Codestyle
      run: dotnet format --verify-no-changes
      working-directory: demo/dotnet
