name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - '.github/workflows/nodejs.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - '.github/workflows/nodejs.yml'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Setup build
        run: yarn prepare

      - name: Build
        run: yarn build

      # GitHub Actions runners do not have sound cards, so a virtual one must be created in order for unit tests to run.
      - name: Install PulseAudio on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio
          pulseaudio --check || pulseaudio --start
          pactl load-module module-null-sink sink_name=vspeaker sink_properties=device.description=virtual_speaker

      - name: Test
        run: yarn test

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-32, rpi5-64, pv-windows, pv-ios]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Setup build
        run: yarn prepare

      - name: Build
        run: yarn build

      - name: Install PulseAudio
        if: matrix.machine == 'rpi3-32' ||
            matrix.machine == 'rpi3-64' ||
            matrix.machine == 'rpi4-32' ||
            matrix.machine == 'rpi4-64'
        run: |
          sudo apt-get update
          sudo apt-get install -y pulseaudio
          pulseaudio --check || pulseaudio --start
          pactl load-module module-null-sink sink_name=vspeaker sink_properties=device.description=virtual_speaker

      - name: Test
        run: yarn test